### ISSUE TITLE
wrong cheese for pneumatic

### ISSUE THREAD

**Issue by quasarqueen** [DevJackSmith/mh-map-helper#23]
http://mhwiki.hitgrab.com/wiki/index.php/Pneumatic_Dirt_Displacement_Mouse
Accidentally been hunting with the wrong cheese after this guy because i didn't bother to double check: your site and the wiki disagree! ;)

**Comment by logicalup** [comment]
wiki is wrong! lol j/k. Thanks for reporting this. Actually on wiki chart of all mice it says otherwise... not sure which one is correct: http://mhwiki.hitgrab.com/wiki/index.php/Mice#P vs your link.

**Comment by quasarqueen** [comment]
Its right on the individual page for the mouse but not on the list you sent. A) just caught it with PP not string and b) the mouse image is brown (those ones are attracted to PP)
But not sure what you can do about it! Maybe I'll send a note to the wiki somehow?
-becs

**Comment by logicalup** [comment]
I'll post it on wiki contributors forums to correct it and will fix it in
my tool. Ty :)

**Comment by quasarqueen** [comment]
No, thank you! This is a great tool! I post it in the comments of every map I'm on. Very awesome since the addition of the rainbows!
I'm a coder, mostly baby stuff, but I appreciate the effort you've put in for the rest of us! :)

**Comment by logicalup** [comment]
notified official wiki contributors: https://www.mousehuntgame.com/forum/showthread.php?85374-The-Official-Wiki-Suggestion-Thread%B2&p=1304637&viewfull=1#post1304637

**Comment by logicalup** [comment]
finally migrated this app to a new platform, and fixed this.
